export const SET_USER = "SET_USER";
export const TOGGLEFETCHINGSTATE = "TOGGLEFETCHINGSTATE";
export const UPDATE_USERDETAILS = "UPDATE_USERDETAILS";
export const SET_POSTS = "SET_POSTS";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_OTP_SECRET = "UPDATE_OTP_SECRET";
export const EDIT_PROFILE = "EDIT_PROFILE";
